spring.application.name=my-first-spring-ai
spring.main.banner-mode=off
# helps in configuring multiple clients
# spring.ai.chat.client.enabled=false
# OpenAI config
spring.ai.openai.api-key=${LM_STUDIO_API_KEY:dummy}
spring.ai.openai.base-url=http://localhost:1234
# spring.ai.openai.chat.options.model=google/gemma-3-4b
spring.ai.openai.chat.options.model=qwen/qwen3-vl-4b
spring.ai.openai.embedding.options.model=text-embedding-nomic-embed-text-v1.5

# Anthropic Claude config
# spring.ai.anthropic.api-key={LM_STUDIO_API_KEY}
# spring.ai.anthropic.base-url=http://localhost:1234
# spring.ai.anthropic.chat.options.model=qwen/qwen3-vl-4b



